title: Виталик Широков
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: auto
  date_format: "%d.%m.%Y %H:%M"
  hide_site_feed_link: true
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/vitalikxp"
    - title: XBOX
      icon: xbox
      url: "https://xbox.com/play/user/Vitalik+Dev"
    - title: Steam
      icon: steam
      url: "https://steamcommunity.com/id/vitalikxp/"
